### PR TITLE
add admin sales cmd

### PR DESCRIPTION
**Pull request by elv-todd**
will let the reviewers decide format

https://github.com/eluv-io/elv-live-js/pull/148 uses try/catch under the covers

this PR uses explicit:

```
$ ./elv-live tenant_primary_sales $TENANT iq__MDEUdJkpiZW7tbPSh9FfEpZfcbK --admin
```

### CODE REVIEW

**Review by elv-serban — COMMENTED** [review]
I think the simplest way to do this would be to add `--admin` to the existing tenant sales command and just use that flag to call `/adm` instead of `/tnt`

That way we don't add a new command and we can use this flag in other commands maybe if needed in the future.

**Comment by elv-todd** [comment]
will do, i like it

**Comment by elv-todd** [comment]
test with, eg, 
```
$ ./elv-live tenant_primary_sales iten3wk48FXDEcnTLsQmQaAizfWWB9M6 iq__MDEUdJkpiZW7tbPSh9FfEpZfcbK --offset 1 --as_url https://host-76-74-28-232.contentfabric.io/as --use_admin_api | head
Tenant Primary Sales: iten3wk48FXDEcnTLsQmQaAizfWWB9M6 iq__MDEUdJkpiZW7tbPSh9FfEpZfcbK
Processor:
Offset: 1
CSV: undefined
use_admin_api: true
Network: main
- ident: 'stripe:cus_OYoKXzWIq5hnbw'
  trans_id: M-6JbRP7anuXTm49MaMamD5r
  addr: '0x172d794c293586ed680b9bc6c1d086f041f53214'
  name: 'Switchyard Sessions Collector''s Edition: Bronze'
```

**Review by elv-serban — APPROVED** [review]
Looks great!

**Pull request merged**
