### PR TITLE
Add NTP sample

### PR DESCRIPTION
**Pull request by elv-serban**
Code sample showing:
- how to create and update NTP instances (class 4)
- how to create embed URLs using ticket codes

### CODE REVIEW

**Comment by elv-todd** [comment]
missing something?

```
$ node samples/NtpSample.js
NEW NTP QOTPSq4aBkiGvjN
CODES [
  { token: '2GDq6F', user_id: 'iusr2cAqH2VYUZLtNFVebL1Mtwn3dT5b' },
  { token: 'WiwTET', user_id: 'iusr2ZtYebWKEhR4KQedXjzW3rWwYmp7' }
]
EMBED URLS [
  'https://embed.v3.contentfabric.io/?p=&net=demo&oid=iq__2dZdRdqPNQqd7TRuAMNVcTUQ9Mah&ct=h',
  'https://embed.v3.contentfabric.io/?p=&net=demo&oid=iq__2dZdRdqPNQqd7TRuAMNVcTUQ9Mah&ct=h'
]
CODES (EMAIL) [
  {
    token: 'pKpW8J',
    user_id: 'iusrw1gNabGCHAP72E1Z17gJDoGniWo',
    email: 'viewer1@example.com'
  },
  {
    token: '2iW4k1',
    user_id: 'iusr2RcTQt4ypXs5WvoU3jsecKR4bhSW',
    email: 'viewer2@example.com'
  }
]
EMBED URLS (EMAIL) [
  'https://embed.v3.contentfabric.io/?p=&net=demo&oid=iq__2dZdRdqPNQqd7TRuAMNVcTUQ9Mah&ct=h',
  'https://embed.v3.contentfabric.io/?p=&net=demo&oid=iq__2dZdRdqPNQqd7TRuAMNVcTUQ9Mah&ct=h'
]
UPDATED NTP {
  ntpId: 'QOTPSq4aBkiGvjN',
  ntpClass: 'Class 4',
  tenantId: 'iten4TXq2en3qtu3JREnE5tSLRf9zLod',
  kmsId: 'ikms27hsDr6QtmWnJKVFkNzroSGEgjjq',
  objectId: 'iq__2G8JtbyLVUQvG73LWWDMWgBDXvTs',
  updatedAt: 1708044496343,
  startTime: 1704067200000,
  endTime: 1735603200000,
  ticketLength: '6',
  maxRedemptions: '100',
  maxTickets: 0
}
ALL DONE
```

**Comment by elv-sam** [comment]
Hm, yes that output has the same embed URLs for all 4..?

Nitpick but are "`codes2`" and "`urls2`" clear enough? I don't know if we have a convention

**Comment by elv-todd** [comment]
turns out, this depends on an updated elv-client-js PR:
`Extend EmbedUrl to support ticket codes (#260)`

will see about getting elv-live to see that; git pull, npm install, didn't catch it, will work on it.

**Comment by elv-serban** [comment]
The sample deletes the OTP at the end.  So the URLs are invalidated.  To test the URLs, comment out the deletion line!

**Pull request merged**
